const API='https://rebzpikwqxmwajdimfld.supabase.co/rest/v1/';
const KEY='sb_publishable_dvwP1aVUTSHvmNcqn-IDEw_f0R2KO7D';
const headers={apikey:KEY,'Content-Type':'application/json'};
const state={view:'summary',vehicles:[],dealers:[],inquiries:[],reservations:[]};
const app=document.getElementById('app');
const e=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`USD ${Number(v||0).toLocaleString('es-UY')}`;
const vehicleName=v=>`${v.brand||''} ${v.model||''}`.trim();
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers,...(options.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
async function load(){const [vehicles,dealers,inquiries,reservations]=await Promise.allSettled([request('vehicles?select=*&order=created_at.desc'),request('dealerships?select=*&order=name.asc'),request('inquiries?select=*,vehicles(brand,model)&order=created_at.desc'),request('reservations?select=*,vehicles(brand,model)&order=created_at.desc')]);state.vehicles=vehicles.status==='fulfilled'?vehicles.value:[];state.dealers=dealers.status==='fulfilled'?dealers.value:[];state.inquiries=inquiries.status==='fulfilled'?inquiries.value:[];state.reservations=reservations.status==='fulfilled'?reservations.value:[];const dealer=state.dealers[0];if(dealer)document.getElementById('dealer-profile').innerHTML=`${e(dealer.name)}<br><small>${e(dealer.city||'Automotora')}</small>`;render()}
function nav(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
function status(s){return s==='reserved'?'Reservado':s==='sold'?'Vendido':s==='active'?'Activa':s==='contacted'?'Contactado':s==='closed'?'Cerrada':s==='cancelled'?'Cancelada':'Disponible'}
function render(){nav();if(state.view==='summary')summary();if(state.view==='vehicles')vehicles();if(state.view==='inquiries')inquiries();if(state.view==='reservations')reservations();if(state.view==='settings')settings()}
function summary(){const active=state.reservations.filter(r=>r.status==='active').length;app.innerHTML=`<header><div><p class="eyebrow">PANEL DE ADMINISTRACIÓN</p><h1>Buenos días</h1><p class="muted">Inventario conectado a Supabase.</p></div><button onclick="openVehicleForm()">+ Añadir vehículo</button></header><div class="metrics"><article class="metric metric-action" onclick="go('vehicles')"><p>Vehículos publicados</p><strong>${String(state.vehicles.length).padStart(2,'0')}</strong><small>Ver inventario</small></article><article class="metric metric-action" onclick="go('inquiries')"><p>Consultas</p><strong>${String(state.inquiries.length).padStart(2,'0')}</strong><small>Ver seguimiento</small></article><article class="metric metric-action" onclick="go('reservations')"><p>Reservas activas</p><strong>${String(active).padStart(2,'0')}</strong><small>Ver agenda</small></article></div><div class="section-heading"><div><h2>Inventario reciente</h2><p class="muted">Vehículos publicados en AutoVision</p></div><a onclick="go('vehicles')">Ver todos →</a></div><div class="grid">${state.vehicles.slice(0,3).map(card).join('')||'<div class="empty">No hay vehículos cargados.</div>'}</div>`}
function card(v){return `<article class="vehicle" onclick="publicVehicle('${e(v.brand)}','${e(v.model)}')"><img src="${e(v.cover_image_url||'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80')}" alt="${e(vehicleName(v))}"><div class="vehicle-info"><span class="status ${v.status==='reserved'?'reserved':''}">${status(v.status)}</span><h3>${e(vehicleName(v))}</h3><p>${e(v.year)} · ${e(v.transmission||'Automático')} · ${Number(v.mileage||0).toLocaleString('es-UY')} km</p><strong>${money(v.price)}</strong></div></article>`}
function vehicles(){app.innerHTML=`<div class="toolbar"><div><p class="eyebrow">INVENTARIO</p><h1>Vehículos</h1></div><button onclick="openVehicleForm()">+ Añadir vehículo</button></div><div class="records">${state.vehicles.map(v=>`<article class="record"><img src="${e(v.cover_image_url||'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=300&q=70')}" alt=""><div><span class="status ${v.status==='reserved'?'reserved':''}">${status(v.status)}</span><h3>${e(vehicleName(v))}</h3><p>${e(v.year)} · ${money(v.price)} · ${Number(v.mileage||0).toLocaleString('es-UY')} km</p></div><div class="record-actions"><button class="secondary" onclick="openVehicleForm('${v.id}')">Editar</button><button class="secondary" onclick="deleteVehicle('${v.id}')">Eliminar</button></div></article>`).join('')||'<div class="empty">No hay vehículos. Tocá “Añadir vehículo” para cargar el primero.</div>'}</div>`}
function inquiries(){app.innerHTML=`<div class="toolbar"><div><p class="eyebrow">SEGUIMIENTO</p><h1>Consultas</h1></div><button onclick="openInquiryForm()">+ Registrar consulta</button></div><div class="records">${state.inquiries.map(i=>`<article class="record"><div class="status ${i.status==='new'?'new':i.status==='closed'?'closed':''}">${status(i.status)}</div><div><h3>${e(i.customer_name)}</h3><p>${e(i.vehicles?vehicleName(i.vehicles):'Consulta general')} · ${e(i.phone||'Sin teléfono')}</p><p>${e(i.message||'Sin mensaje')}</p></div><div class="record-actions"><button class="secondary" onclick="cycleInquiry('${i.id}','${i.status}')">Cambiar estado</button></div></article>`).join('')||'<div class="empty">Todavía no hay consultas registradas. Las consultas de WhatsApp se pueden agregar aquí para hacer seguimiento.</div>'}</div>`}
function reservations(){app.innerHTML=`<div class="toolbar"><div><p class="eyebrow">AGENDA</p><h1>Reservas</h1></div><button onclick="openReservationForm()">+ Añadir reserva</button></div><div class="records">${state.reservations.map(r=>`<article class="record"><div class="status ${r.status==='cancelled'?'closed':''}">${status(r.status)}</div><div><h3>${e(r.customer_name)}</h3><p>${e(r.vehicles?vehicleName(r.vehicles):'Sin vehículo')} · ${r.scheduled_for?new Date(r.scheduled_for).toLocaleString('es-UY'):'Sin fecha'}</p><p>${e(r.phone||'Sin teléfono')}</p></div><div class="record-actions"><button class="secondary" onclick="cycleReservation('${r.id}','${r.status}')">Cambiar estado</button></div></article>`).join('')||'<div class="empty">Todavía no hay reservas. Podés registrar visitas y señas desde aquí.</div>'}</div>`}
function settings(){const d=state.dealers[0];app.innerHTML=`<div class="toolbar"><div><p class="eyebrow">PERFIL COMERCIAL</p><h1>Configuración</h1></div></div><div class="metric"><h2>${e(d?.name||'Tu automotora')}</h2><p class="muted">Estos datos aparecen en las fichas públicas de los vehículos.</p><button onclick="openDealerForm()">Editar datos de la automotora</button></div>`}
function showModal(title,body){const modal=document.getElementById('modal');modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><p class="eyebrow">AUTOVISION AI</p><h2>${title}</h2>${body}</div>`;modal.hidden=false}
function closeModal(){document.getElementById('modal').hidden=true}
function optionVehicles(value=''){return `<option value="">Seleccionar vehículo</option>${state.vehicles.map(v=>`<option value="${v.id}" ${v.id===value?'selected':''}>${e(vehicleName(v))}</option>`).join('')}`}
function optionDealers(value=''){return `<option value="" disabled ${value?'':'selected'}>Seleccionar automotora</option>${state.dealers.map(d=>`<option value="${d.id}" ${d.id===value?'selected':''}>${e(d.name)}</option>`).join('')}<option value="__new">+ Crear nueva automotora</option>`}
function openVehicleForm(id){const v=state.vehicles.find(x=>x.id===id)||{};const dealerId=v.dealership_id||state.dealers[0]?.id||'';showModal(id?'Editar vehículo':'Añadir vehículo',`<form id="vehicle-form"><label>Automotora<select name="dealership_id" id="dealer-select" required onchange="toggleDealerFields()">${optionDealers(dealerId)}</select></label><div id="new-dealer-fields" hidden><p class="eyebrow">DATOS DE LA NUEVA AUTOMOTORA</p><label>Nombre de la automotora<input name="dealer_name" placeholder="Ej.: Autos del Este"></label><div class="form-row"><label>Ciudad<input name="dealer_city" placeholder="Ej.: Maldonado"></label><label>País<input name="dealer_country" placeholder="Ej.: Uruguay"></label></div><label>WhatsApp de contacto<input name="dealer_whatsapp" placeholder="Ej.: 59899123456"></label><p class="muted">Este número aparecerá en la ficha y recibirá las consultas del QR.</p></div><div class="form-row"><label>Marca<input name="brand" required value="${e(v.brand)}"></label><label>Modelo<input name="model" required value="${e(v.model)}"></label></div><div class="form-row"><label>Año<input name="year" type="number" required value="${e(v.year||new Date().getFullYear())}"></label><label>Precio USD<input name="price" type="number" required value="${e(v.price)}"></label></div><div class="form-row"><label>Kilometraje<input name="mileage" type="number" value="${e(v.mileage||0)}"></label><label>Estado<select name="status">${['available','reserved','sold'].map(s=>`<option value="${s}" ${v.status===s?'selected':''}>${status(s)}</option>`).join('')}</select></label></div><label>Foto desde tu computadora<input name="vehicle_image" type="file" accept="image/jpeg,image/png,image/webp"></label><label>URL de foto<input name="cover_image_url" value="${e(v.cover_image_url)}" placeholder="https://..."></label><label>Descripción<textarea name="description">${e(v.description)}</textarea></label><p class="form-message" id="form-message"></p><button>Guardar vehículo</button></form>`);document.getElementById('vehicle-form').addEventListener('submit',ev=>saveVehicle(ev,id))}
function toggleDealerFields(){const select=document.getElementById('dealer-select'),fields=document.getElementById('new-dealer-fields');if(!select||!fields)return;fields.hidden=select.value!=='__new';fields.querySelectorAll('input').forEach(input=>input.required=select.value==='__new')}
async function saveVehicle(ev,id){ev.preventDefault();const f=new FormData(ev.currentTarget),data=Object.fromEntries(f);const image=f.get('vehicle_image');delete data.vehicle_image;const msg=document.getElementById('form-message');try{if(data.dealership_id==='__new'){if(!data.dealer_name||!data.dealer_whatsapp)throw Error('Completá nombre y WhatsApp de la automotora.');msg.textContent='Creando automotora…';const slug=data.dealer_name.toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-5);const dealer=await request('dealerships',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({slug,name:data.dealer_name,whatsapp:data.dealer_whatsapp.replace(/[^0-9]/g,''),city:data.dealer_city,country:data.dealer_country})});data.dealership_id=dealer[0].id}delete data.dealer_name;delete data.dealer_whatsapp;delete data.dealer_city;delete data.dealer_country;data.year=Number(data.year);data.price=Number(data.price);data.mileage=Number(data.mileage||0);data.currency='USD';data.transmission='Automático';data.fuel_type='No especificado';if(image?.size){msg.textContent='Subiendo foto…';const ext=(image.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');const name=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const r=await fetch(`https://rebzpikwqxmwajdimfld.supabase.co/storage/v1/object/vehicle-images/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':image.type||'image/jpeg','x-upsert':'false'},body:image});if(!r.ok)throw Error();data.cover_image_url=`https://rebzpikwqxmwajdimfld.supabase.co/storage/v1/object/public/vehicle-images/${name}`}await request(id?`vehicles?id=eq.${id}`:'vehicles',{method:id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});closeModal();await load()}catch(error){msg.textContent=error.message||'No se pudo guardar. Revisá que hayas iniciado sesión.'}}
async function deleteVehicle(id){if(!confirm('¿Eliminar este vehículo?'))return;try{await request(`vehicles?id=eq.${id}`,{method:'DELETE'});await load()}catch{alert('No se pudo eliminar el vehículo.')}}
function openInquiryForm(){showModal('Registrar consulta',`<form id="inquiry-form"><label>Vehículo<select name="vehicle_id">${optionVehicles()}</select></label><label>Nombre del cliente<input name="customer_name" required></label><label>Teléfono<input name="phone"></label><label>Mensaje<textarea name="message"></textarea></label><button>Guardar consulta</button></form>`);document.getElementById('inquiry-form').addEventListener('submit',ev=>saveRecord(ev,'inquiries'))}
function openReservationForm(){showModal('Añadir reserva',`<form id="reservation-form"><label>Vehículo<select name="vehicle_id" required>${optionVehicles()}</select></label><label>Nombre del cliente<input name="customer_name" required></label><div class="form-row"><label>Teléfono<input name="phone"></label><label>Fecha y hora<input name="scheduled_for" type="datetime-local"></label></div><label>Notas<textarea name="notes"></textarea></label><button>Guardar reserva</button></form>`);document.getElementById('reservation-form').addEventListener('submit',ev=>saveRecord(ev,'reservations'))}
async function saveRecord(ev,table){ev.preventDefault();try{await request(table,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.currentTarget)))});closeModal();await load()}catch{alert('No se pudo guardar. Revisá que hayas iniciado sesión y ejecutado modules.sql en Supabase.')}}
async function cycleInquiry(id,current){const next=current==='new'?'contacted':current==='contacted'?'closed':'new';await request(`inquiries?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:next})});await load()}
async function cycleReservation(id,current){const next=current==='active'?'completed':current==='completed'?'cancelled':'active';await request(`reservations?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:next})});await load()}
function openDealerForm(){const d=state.dealers[0]||{};showModal('Datos de la automotora',`<form id="dealer-form"><label>Nombre<input name="name" required value="${e(d.name)}"></label><label>WhatsApp con código de país<input name="whatsapp" required value="${e(d.whatsapp)}"></label><div class="form-row"><label>Ciudad<input name="city" value="${e(d.city)}"></label><label>País<input name="country" value="${e(d.country)}"></label></div><label>URL del logo<input name="logo_url" value="${e(d.logo_url)}"></label><button>Guardar configuración</button></form>`);document.getElementById('dealer-form').addEventListener('submit',async ev=>{ev.preventDefault();try{await request(`dealerships?id=eq.${d.id}`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(ev.currentTarget)))});closeModal();await load()}catch{alert('No se pudo guardar la configuración.')}})}
function go(view){state.view=view;render()}function publicVehicle(brand,model){location.href=`vehicle.html?brand=${encodeURIComponent(brand)}&model=${encodeURIComponent(model)}`}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));load();

// Amplía el formulario básico sin cambiar el flujo de guardado existente.
const openBasicVehicleForm=openVehicleForm;
window.openVehicleForm=function(id){
  openBasicVehicleForm(id);
  const v=state.vehicles.find(x=>x.id===id)||{};
  const form=document.getElementById('vehicle-form');
  const description=form.querySelector('textarea[name="description"]');
  description.insertAdjacentHTML('beforebegin',`<p class="eyebrow">DATOS TÉCNICOS DEL VEHÍCULO</p><div class="form-row"><label>Motor<input name="engine" value="${e(v.engine)}" placeholder="Ej.: 2.0 TFSI Turbo nafta"></label><label>Cilindrada<input name="displacement" value="${e(v.displacement)}" placeholder="Ej.: 1.984 cc"></label></div><div class="form-row"><label>Potencia<input name="power" value="${e(v.power)}" placeholder="Ej.: 230 HP"></label><label>Tracción<input name="drivetrain" value="${e(v.drivetrain)}" placeholder="Ej.: Quattro"></label></div><div class="form-row"><label>Transmisión<input name="transmission_detail" value="${e(v.transmission_detail||v.transmission)}" placeholder="Ej.: Automática"></label><label>Combustible<input name="fuel_type_detail" value="${e(v.fuel_type_detail||v.fuel_type)}" placeholder="Ej.: Nafta"></label></div><label>Equipamiento destacado<textarea name="featured_equipment" placeholder="Ej.: Ópticas LED, cámara, sensores, cuero, techo panorámico...">${e(v.featured_equipment)}</textarea></label><label>Fotos adicionales para la galería<input name="gallery_images" type="file" multiple accept="image/jpeg,image/png,image/webp"></label><p class="muted">Podés elegir varias fotos a la vez. La primera foto del formulario sigue siendo la portada.</p>`);
  form.addEventListener('submit',ev=>{ev.preventDefault();ev.stopImmediatePropagation();saveVehicleWithGallery(ev,id)},true);
}

async function saveVehicleWithGallery(ev,id){
  const f=new FormData(ev.currentTarget),data=Object.fromEntries(f),image=f.get('vehicle_image'),galleryImages=f.getAll('gallery_images').filter(file=>file&&file.size);
  delete data.vehicle_image;delete data.gallery_images;
  const msg=document.getElementById('form-message');
  try{
    if(data.dealership_id==='__new'){
      if(!data.dealer_name||!data.dealer_whatsapp)throw Error('Completá nombre y WhatsApp de la automotora.');
      msg.textContent='Creando automotora…';
      const slug=data.dealer_name.toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-5);
      const dealer=await request('dealerships',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({slug,name:data.dealer_name,whatsapp:data.dealer_whatsapp.replace(/[^0-9]/g,''),city:data.dealer_city,country:data.dealer_country})});
      data.dealership_id=dealer[0].id;
    }
    delete data.dealer_name;delete data.dealer_whatsapp;delete data.dealer_city;delete data.dealer_country;
    data.year=Number(data.year);data.price=Number(data.price);data.mileage=Number(data.mileage||0);data.currency='USD';data.transmission=data.transmission_detail||'Automático';data.fuel_type=data.fuel_type_detail||'No especificado';
    if(image?.size){msg.textContent='Subiendo foto principal…';data.cover_image_url=await uploadVehicleImage(image)}
    const saved=await request(id?`vehicles?id=eq.${id}`:'vehicles',{method:id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});
    const vehicleId=id||saved?.[0]?.id;
    for(let index=0;index<galleryImages.length;index++){
      msg.textContent=`Subiendo foto ${index+1} de ${galleryImages.length}…`;
      const imageUrl=await uploadVehicleImage(galleryImages[index]);
      await request('vehicle_images',{method:'POST',body:JSON.stringify({vehicle_id:vehicleId,image_url:imageUrl,sort_order:index})});
    }
    closeModal();await load();
  }catch(error){msg.textContent=error.message||'No se pudo guardar. Revisá tu sesión y que hayas ejecutado los archivos SQL.'}
}

async function uploadVehicleImage(file){
  const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');
  const name=`${Date.now()}-${crypto.randomUUID()}.${ext}`;
  const r=await fetch(`https://rebzpikwqxmwajdimfld.supabase.co/storage/v1/object/vehicle-images/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':file.type||'image/jpeg','x-upsert':'false'},body:file});
  if(!r.ok)throw Error('No se pudo subir una de las fotos.');
  return `https://rebzpikwqxmwajdimfld.supabase.co/storage/v1/object/public/vehicle-images/${name}`;
}
